version: '3.8'

services:
  db:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: music_library
      # https://stackoverflow.com/questions/60193781/postgres-with-docker-compose-gives-fatal-role-root-does-not-exist-error/60194261#60194261
      PGUSER: postgres
    ports:
      - "7000:5432"
    # https://stackoverflow.com/questions/65115627/safe-ways-to-specify-postgres-parameters-for-healthchecks-in-docker-compose
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "music_library"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s  
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "9090:9090"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - configs/docker.env

volumes:
  postgres_data: