openapi: 3.0.0
info:
  title: Music Library API
  description: API for managing music library operations.
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /api/v1/add:
    post:
      summary: Add a new song
      description: Adds a new song to the music library.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                group:
                  type: string
                release:
                  type: string
                  format: date
                text:
                  type: string
                link:
                  type: string
      responses:
        '200':
          description: Song successfully added
        '400':
          description: Bad request, invalid input data
        '500':
          description: Internal server error

  /api/v1/get/filtration:
    get:
      summary: Filter songs by group
      description: Retrieves songs filtered by group with pagination.
      parameters:
        - in: query
          name: group
          required: true
          schema:
            type: string
        - in: query
          name: records
          required: true
          schema:
            type: integer
        - in: query
          name: page
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: List of songs matching the criteria
        '400':
          description: Bad request, missing required parameters
        '500':
          description: Internal server error

  /api/v1/update:
    put:
      summary: Update a song
      description: Updates an existing song's details.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                name:
                  type: string
                group:
                  type: string
                release:
                  type: string
                  format: date
                text:
                  type: string
                link:
                  type: string
      responses:
        '200':
          description: Song successfully updated
        '400':
          description: Bad request, invalid or missing input data
        '500':
          description: Internal server error

  /api/v1/get/text/pagina:
    get:
      summary: Get song text with pagination
      description: Retrieves the text of a song with pagination.
      parameters:
        - in: query
          name: id
          required: true
          schema:
            type: string
        - in: query
          name: couplet
          required: true
          schema:
            type: integer
        - in: query
          name: page
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Song text retrieved successfully
        '400':
          description: Bad request, invalid input parameters
        '500':
          description: Internal server error

  /metrics:
    get:
      summary: Get metrics
      description: Retrieves metrics for the application.
      responses:
        '200':
          description: Metrics retrieved successfully
        '500':
          description: Internal server error

  /api/v1/delete/{id}:
    delete:
      summary: Delete a song
      description: Deletes a song from the library using its ID.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Song successfully deleted
        '400':
          description: Bad request, invalid ID
        '500':
          description: Internal server error
